---
metadata:
  name: barman-secrets
  namespace: outline
stringData:
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:HixrAX13gQCRmCOV8aXbLFEHeg31CD+r,iv:S0E6Wvw+ndLpvr9W93oenxdCgzeiWenhuQhB0sB7t2Y=,tag:a0denxZugoT4GXJd36iBWg==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:vuEp/JuxgVwuIFnyFyEbxx2XHxMlC1D92A8=,iv:fEnAvOUTXAxMZ5AgDWgWyCpNxe4SqB5jutpCl9+5mt8=,tag:EvTUXeRVjRRKitGtAN2oGg==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:GLKyEZXQ3r4Vq+TYbDdyWTHM5XBqTUIVlL1/qt3l,iv:IM0NyYsVhdWnma9Iiy+TBio9iHDDMeu+eqqd+TDBGOc=,tag:3YBSlqickdKv+QE5frLLxw==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVBGYmVYVzRVS1BZdWRK
        TWFYOXJONnZIVU5rSDNHS1lTRHFJaUxiUVhVCnpFZ2V6UFgwMDV3azlDb016bXF0
        YW1JMHRzY2RIcGZmTFl4SWdJYlBDRTQKLS0tIDJlVExTc0xZSlJTb2g0QVBSTEdS
        UW9QdlNlTEdFdlN0azNobVVaQjliQW8K+W8b6/j3D6HJX+AdaJJCotdgHk2Anqn3
        svTcLSuswI4LPbnON4vTB8nIr6Thj+IU0HSbR7hie3wrGSvms2JCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-28T20:01:29Z'
  mac: ENC[AES256_GCM,data:9EudbpouCd4ztY01+kebTZdE4PsIcy3e+9ZXtqoy+pohsgihtOSFYX6lbeBBs59EZizwkU08aYQAUJtYrga0WZxviDW2zbSY25MfKEjMkH4cS1tFaA6psjw+quO+qjsS1dOF/Ee5qEbTU9tyOYM03BNmDZSluhXVWU+AoTZMPZE=,iv:h+YmF1Elqdw9o4V+my/ZABmzuFV/85B3F6BmYaAlXek=,tag:8/Nz2Y6IGhkwp1aRnAjcXw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: outline-secrets
  namespace: outline
stringData:
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:I/jS5bI8heHJaRWcfHwkPg==,iv:+Llpg4pAzTuXHdUNyJxG4Q6boFgV550B0GZSfoRfAjg=,tag:eJCw9uMOAzI51IfbPdaR5Q==,type:str]
  SMTP_MAIL: ENC[AES256_GCM,data:llblMsOBg23ptyII06WGRYWdzg==,iv:FF03bypQ3PNFhBgWaAPYYymv9hJ0ZzjiSVm7+U5aVcQ=,tag:8oAjXj6s2le29qWFW83YNA==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:nvu2egHFqsll/OTPEFR+4C76uvxVJVE=,iv:7WYMh8MI4IUuk2K0f6tx3wJq6zE3CDreBM//J+VtsJE=,tag:LrBD6T0+0gIis/PBMKPtag==,type:str]
  K8UP_B2_BUCKET_NAME: ENC[AES256_GCM,data:0tXppaezPJbEuxPe3C1FCEtisUDjeg==,iv:BNnFBQ6Y6qaRxDvd495lbi4AnMQRhBDjZ+Wsjb8QUys=,tag:Ekl94mD+SOnxrSPGl+PgiA==,type:str]
  K8UP_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:esQ9Ax3P2dDACt/Qdu0JGReMFOo8Knf2,iv:1cJTk4fomKzD9LM96vrM5eSTFUcXYYUjrCxehoPf2ss=,tag:KRuQOFvUQ7aANAvjMNpwCg==,type:str]
  K8UP_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:p4vwfkCs12+P+uI9iuptzM4t0RaVzQcLyNm3Ng==,iv:ho2hnAj6qtfylSx7xqBVl89VOsWy1bQRkLR0hOseqrY=,tag:gMjdLW+AE4f637vq5s9Haw==,type:str]
  K8UP_RESTIC_KEY: ENC[AES256_GCM,data:nC1o2s5wMM44msHiRnrH+J6b,iv:Z+TXpS5/O4SM5Kx/+yKbEWXddFYbFFkuh0e6BEjKAtg=,tag:P2SOrqZVSFQGEe1TY/K2hg==,type:str]
  OUTLINE_DATABASE_URL: ENC[AES256_GCM,data:w03JLmkqUL83Ol88oJktgQL0ogG0bMM0ujTKfqotYBU323w86UDSOVvnWytmXcUC+Y2QQq/SBPcu4iTpt9KeNlvIb3byqks89QP9gpG9rGpk07/eDc2QBi5RKLRPcqYlMjooRPcVr/608zquGbmHmVmuqMd2Uzu7bN2TY+p/8HCylZlNoEEaWQ==,iv:f5RJLv3fdCCR8SJGi32GoeM5m5i8gG2zo2+lhfyg0W0=,tag:DDFJjvMvc5SWEZ5eAczdRQ==,type:str]
  OUTLINE_SECRET_KEY: ENC[AES256_GCM,data:C7D9zd242XNIygL9YlUY1sKyXnQ33pr6fFWJ3psXDv53oTFP9QT7stHCiN9J5x1ovOBveDl61b0msYybSpmeNQ==,iv:YXSb4tHr6Z6asbM2vc3xjVczQiA3Xdcw2YUA3tNECqg=,tag:ETgHMwmg148YIv3ZV+4nYg==,type:str]
  OUTLINE_UTILS_SECRET: ENC[AES256_GCM,data:AvXQUvMYgbAO2ETawouWxHUFAuOJPyFFaizRVpmiIcq3cNDRq31xeRN8a4YhxLr/29r6Nn+91qrfbWvC5lnbLg==,iv:WahhZa5IangdqZlgya5I4rrk+3Awm2YI6GVAGqjitnw=,tag:AEhZ/mv9ZOyZz5O5DY0dzQ==,type:str]
  OUTLINE_S3_SECRET_ID: ENC[AES256_GCM,data:UaLYfzelA7lgz1U5ElGzuJBAI7Q=,iv:2DFPOi4or4gNZdpOPqG5CgAUhu7dnwwRPZ9V/+Vc5ho=,tag:ozww6CuIaxAY2mvvRDBSlQ==,type:str]
  OUTLINE_S3_SECRET_KEY: ENC[AES256_GCM,data:/4/qJa41cCRTNp1e6evDAAZR69dvz0RgeYXS/zbe6YCzwjaKNuFHag==,iv:H3jkphLb4EwU7GyRrgNK+lBf5YQZkEYeh2Frex+deXI=,tag:VpYGWq3nRsW6itkFgGh00A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVBGYmVYVzRVS1BZdWRK
        TWFYOXJONnZIVU5rSDNHS1lTRHFJaUxiUVhVCnpFZ2V6UFgwMDV3azlDb016bXF0
        YW1JMHRzY2RIcGZmTFl4SWdJYlBDRTQKLS0tIDJlVExTc0xZSlJTb2g0QVBSTEdS
        UW9QdlNlTEdFdlN0azNobVVaQjliQW8K+W8b6/j3D6HJX+AdaJJCotdgHk2Anqn3
        svTcLSuswI4LPbnON4vTB8nIr6Thj+IU0HSbR7hie3wrGSvms2JCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-28T20:01:29Z'
  mac: ENC[AES256_GCM,data:9EudbpouCd4ztY01+kebTZdE4PsIcy3e+9ZXtqoy+pohsgihtOSFYX6lbeBBs59EZizwkU08aYQAUJtYrga0WZxviDW2zbSY25MfKEjMkH4cS1tFaA6psjw+quO+qjsS1dOF/Ee5qEbTU9tyOYM03BNmDZSluhXVWU+AoTZMPZE=,iv:h+YmF1Elqdw9o4V+my/ZABmzuFV/85B3F6BmYaAlXek=,tag:8/Nz2Y6IGhkwp1aRnAjcXw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: outline-oidc-secrets
  namespace: outline
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: authelia/authelia-oidc-secrets
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVBGYmVYVzRVS1BZdWRK
        TWFYOXJONnZIVU5rSDNHS1lTRHFJaUxiUVhVCnpFZ2V6UFgwMDV3azlDb016bXF0
        YW1JMHRzY2RIcGZmTFl4SWdJYlBDRTQKLS0tIDJlVExTc0xZSlJTb2g0QVBSTEdS
        UW9QdlNlTEdFdlN0azNobVVaQjliQW8K+W8b6/j3D6HJX+AdaJJCotdgHk2Anqn3
        svTcLSuswI4LPbnON4vTB8nIr6Thj+IU0HSbR7hie3wrGSvms2JCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-28T20:01:29Z'
  mac: ENC[AES256_GCM,data:9EudbpouCd4ztY01+kebTZdE4PsIcy3e+9ZXtqoy+pohsgihtOSFYX6lbeBBs59EZizwkU08aYQAUJtYrga0WZxviDW2zbSY25MfKEjMkH4cS1tFaA6psjw+quO+qjsS1dOF/Ee5qEbTU9tyOYM03BNmDZSluhXVWU+AoTZMPZE=,iv:h+YmF1Elqdw9o4V+my/ZABmzuFV/85B3F6BmYaAlXek=,tag:8/Nz2Y6IGhkwp1aRnAjcXw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: outline-db-root-credentials
  namespace: outline
stringData:
  username: ENC[AES256_GCM,data:2aaKf9F6BhQ=,iv:oWaML7w7sd3XtUkzpNffCMqerjonA3c9K8FgUL0yeKQ=,tag:xm/17pJcApQOAxhILHUWXA==,type:str]
  password: ENC[AES256_GCM,data:nnagjdxRrTyJJiHMNJRabZPFtmfy+9TI6T7v4SUhSzkJinqtjOYVXfaxg+Kp5RqqBqncD74AgzhcHr8gKUgJ4Q==,iv:tbzAemT9RBNebEKtOiS5UIzhFsH4Rln4uVb+OEL1MvE=,tag:+j65gqFUusmV5oWVhLmLNw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVBGYmVYVzRVS1BZdWRK
        TWFYOXJONnZIVU5rSDNHS1lTRHFJaUxiUVhVCnpFZ2V6UFgwMDV3azlDb016bXF0
        YW1JMHRzY2RIcGZmTFl4SWdJYlBDRTQKLS0tIDJlVExTc0xZSlJTb2g0QVBSTEdS
        UW9QdlNlTEdFdlN0azNobVVaQjliQW8K+W8b6/j3D6HJX+AdaJJCotdgHk2Anqn3
        svTcLSuswI4LPbnON4vTB8nIr6Thj+IU0HSbR7hie3wrGSvms2JCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-28T20:01:29Z'
  mac: ENC[AES256_GCM,data:9EudbpouCd4ztY01+kebTZdE4PsIcy3e+9ZXtqoy+pohsgihtOSFYX6lbeBBs59EZizwkU08aYQAUJtYrga0WZxviDW2zbSY25MfKEjMkH4cS1tFaA6psjw+quO+qjsS1dOF/Ee5qEbTU9tyOYM03BNmDZSluhXVWU+AoTZMPZE=,iv:h+YmF1Elqdw9o4V+my/ZABmzuFV/85B3F6BmYaAlXek=,tag:8/Nz2Y6IGhkwp1aRnAjcXw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
# Only needed for bootstraping
apiVersion: v1
kind: Secret
metadata:
  name: outline-db-app-credentials
  namespace: outline
stringData:
  username: ENC[AES256_GCM,data:oKECENB2SA==,iv:2P23l1Om1jgNiC+aJoixlM5rksUdAVVJ2uvKcBOqWU8=,tag:zpNtAqCEcqubNncX7LoAFQ==,type:str]
  password: ENC[AES256_GCM,data:WVPA3NlnXVYKMN9DIhaczTV/TVh7tR36huDNw8JeFeSLEq+r/KX016NCEmJMD5Uuf/MxauP62rG1suJQhAvxHg==,iv:QZ4OOM6vBSvlifv+YhPUzBgNUwhDuZQM096bAJ/X6fA=,tag:153X0mCcvSYV5VJTSBphEg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJRVBGYmVYVzRVS1BZdWRK
        TWFYOXJONnZIVU5rSDNHS1lTRHFJaUxiUVhVCnpFZ2V6UFgwMDV3azlDb016bXF0
        YW1JMHRzY2RIcGZmTFl4SWdJYlBDRTQKLS0tIDJlVExTc0xZSlJTb2g0QVBSTEdS
        UW9QdlNlTEdFdlN0azNobVVaQjliQW8K+W8b6/j3D6HJX+AdaJJCotdgHk2Anqn3
        svTcLSuswI4LPbnON4vTB8nIr6Thj+IU0HSbR7hie3wrGSvms2JCYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-28T20:01:29Z'
  mac: ENC[AES256_GCM,data:9EudbpouCd4ztY01+kebTZdE4PsIcy3e+9ZXtqoy+pohsgihtOSFYX6lbeBBs59EZizwkU08aYQAUJtYrga0WZxviDW2zbSY25MfKEjMkH4cS1tFaA6psjw+quO+qjsS1dOF/Ee5qEbTU9tyOYM03BNmDZSluhXVWU+AoTZMPZE=,iv:h+YmF1Elqdw9o4V+my/ZABmzuFV/85B3F6BmYaAlXek=,tag:8/Nz2Y6IGhkwp1aRnAjcXw==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
